// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO4X24aKxH5tChfT0KkKetieNtxuiLsKA',
    appId: '1:671924222085:android:59480aa96c3c8f6dc751ec',
    messagingSenderId: '671924222085',
    projectId: 'alcheringa2022',
    databaseURL: 'https://alcheringa2022-default-rtdb.firebaseio.com',
    storageBucket: 'alcheringa2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFoSDv_6Nukf8_Xut2aVxzwk3ZQmoAM_g',
    appId: '1:671924222085:ios:1e0b9dd7c95ec6e0c751ec',
    messagingSenderId: '671924222085',
    projectId: 'alcheringa2022',
    databaseURL: 'https://alcheringa2022-default-rtdb.firebaseio.com',
    storageBucket: 'alcheringa2022.appspot.com',
    androidClientId: '671924222085-1jhjg9e6eo9rotu54fllrui8k55pscjd.apps.googleusercontent.com',
    iosClientId: '671924222085-qstesm3d3i1310ncs0rsevgjcl65knj3.apps.googleusercontent.com',
    iosBundleId: 'com.alcheringa.alcheringa',
  );

}